version: "3.5"

services:

  home_dnscrypt:
    build: ./dnscrypt
    image: dnscrypt-custom:v2.0.45
    container_name: dnscrypt
    networks:
      dns_net:
        ipv4_address: 10.53.53.100
        ipv6_address: 2001:3984:3989::10
    restart: unless-stopped    


  home_pihole:
    container_name: pihole
    image: pihole/pihole:v5.8.1
    networks:
      dns_net:
        ipv4_address: 10.53.53.200
        ipv6_address: 2001:3984:3989::20
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      #- "80:80/tcp"
      #- "443:443/tcp"
    environment:
      TZ: 'Europe/Paris'
      WEBPASSWORD: 'strong_password_(G3fvca#AZDEFR€3µ$d:qd$aq?fe' # to change manually, plus the web admin interface is not exposed
      PIHOLE_DNS_: 10.53.53.100#5353;2001:3984:3989::20#53530
    dns:
      - 127.0.0.1
    volumes:
       - './etc-pihole/:/etc/pihole/'
       - './etc-dnsmasq.d/:/etc/dnsmasq.d/'
    restart: unless-stopped
    depends_on:
      - home_dnscrypt



networks:
  dns_net:
    driver: bridge
    ipam:
      config:
        - subnet: "10.53.53.0/24"
        - subnet: "2001:3984:3989::/64"
